# Generated by Django 2.2.6 on 2019-11-29 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('admin', 'Es administrador'), ('lector', 'Es lector'))},
        ),
    ]
